### ISSUE TITLE
Hebmorph for android

### ISSUE THREAD

**Issue by naory159** [synhershko/HebMorph#50]
Hi

I'm able to run the hebmorph on Android device.
But loading the dictionary take very long time! About 3 minutes.

It is possible to reduce the time to load the dictionary?

**Comment by synhershko** [comment]
Dictionary loading takes a few seconds on beefy servers as well, and is optimised in the commercial version. You are welcome to play around with the OSS code in this repo and send a PR that optimises loading time.

**Comment by naory159** [comment]
Do you have any idea?

**Comment by synhershko** [comment]
Idea for what?

**Comment by naory159** [comment]
How to optimises loading time.

**Comment by synhershko** [comment]
The hspell files are harder to optimize for. Like I said, we already did this for the dictionaries of the commercial version.

**Comment by naory159** [comment]
Well, when i pass `false` to the constructor of `HSpellLoader`, the the loading time now is about 1 minute! very good!
But, When i do the search after the dictionary load, i get this error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference`,
`at com.code972.hebmorph.MorphData.getLemmas(MorphData.java:100)`

**Comment by synhershko** [comment]
This sounds like a bug, and will be happy to have a pull request for fixing it

**Comment by naory159** [comment]
OK. Hope the bug will be fix fast

**Comment by synhershko** [comment]
Please provide a more descriptive bug report in another issue
