### ISSUE TITLE
Update to Hspell 1.4

### ISSUE THREAD

**Issue by evyatar** [synhershko/HebMorph#58]
Would you please update to Hspell 1.4 (released on June 24th, 2017)?

**Comment by synhershko** [comment]
We will accept a PR for it, it's not a priority for us at this point. If you wish to use a better dictionary we provide one as part of the commercial license we are offering.

**Comment by Sternbach-Software** [comment]
@synhershko I generated these files - is this enough? It said there was an error in make install, so some files may not have been created (using macOS).

hebrew.wgz
hebrew.wgz.hints
hebrew.wgz.prefixes
hebrew.wgz.sizes

**Comment by synhershko** [comment]
Sorry , this is not a priority for us anymore. You are welcome to check https://ey.fo/ if you need a good Hebrew analyzer.
