### ISSUE TITLE
Is this still working with recent Solr versions?

### ISSUE THREAD

**Issue by ZvikaZ** [synhershko/HebMorph#65]
Hi.

I see that there wasn't any commit for a long time.
Is HebMorph still working with recent Solr versions, such as 9.1?

Thanks

**Comment by synhershko** [comment]
We thank you for you interest.

We have recent versions released and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Solr and Elasticsearch version. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion, or reach out at https://ey.fo/he/contact
